### ISSUE TITLE
Tutorial Plots - Add legends where missing

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/superphot-plus#101]
Very minor point: Several plots have multiple bands co-plotted in the tutorial, it would probably be best to be explicit and add legends labeling the bands.

**Comment by dougbrn** [comment]
Also, very very minor: Red-Green as a distinguishing color pair can be hard from an accessibility stand-point (red-green colorblindness is the most common type). Either changing the colors, or using different symbols would help.

**Comment by jeremykubica** [comment]
Did #116 completely fix this? Or is there still more to do?
