### ISSUE TITLE
Use tempfile for temporary test files

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/superphot-plus#81]
Currently, `test_data_dir` is used in two ways: to get test data (see fixtures in `conftest.py`) and to output temporary files which then are supposed to be deleted (see `test_plotting.py`). I believe that these two directories should be different and a new temporal directory should be created for each tests generating temporary files. Standard library module [`tempfile`](https://docs.python.org/3.8/library/tempfile.html) can be used for that.

**Comment by delucchi-cmu** [comment]
If tests are writing temporary files, they can use the pytest-provided `tmp_path` fixture. `test_data_dir` should be used for input paths, where `/tests/data` contains some simple golden files.

The usage in `test_plotting` should be updated to use `tmp_path` for writing new plot files.

**Comment by hombit** [comment]
@delucchi-cmu you are right, `tmp_path` fits perfectly
